// flow-typed signature: fe1d6f8e70784a95450ff25905bc0290
// flow-typed version: <<STUB>>/material-icons_v^0.1.0/flow_v0.58.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'material-icons'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'material-icons' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'material-icons/gulpfile' {
  declare module.exports: any;
}

declare module 'material-icons/src/map' {
  declare module.exports: any;
}

// Filename aliases
declare module 'material-icons/gulpfile.js' {
  declare module.exports: $Exports<'material-icons/gulpfile'>;
}
declare module 'material-icons/src/map.js' {
  declare module.exports: $Exports<'material-icons/src/map'>;
}
