// flow-typed signature: a9749140250833ee73dd729a7e25cd14
// flow-typed version: <<STUB>>/typeface-faster-one_v0.0.35/flow_v0.58.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'typeface-faster-one'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'typeface-faster-one' {
  declare module.exports: any;
}
