// flow-typed signature: a1dc2a9a38447415d4b8becb4595c777
// flow-typed version: <<STUB>>/typeface-roboto_v0.0.35/flow_v0.58.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'typeface-roboto'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'typeface-roboto' {
  declare module.exports: any;
}
